@api = http://localhost:3002/financial

GET {{api}}/users

###

GET {{api}}/users/15

###

GET {{api}}/user/4/incomes

###

PUT {{api}}/users/1/update
Content-Type: application/json

{
    "userName": "Teo",
    "name": "Mateo Loaiza Correa",
    "password": "01800MaT*",
    "email": "matiu0330@gmail.com"
}

###

POST {{api}}/newUser
Content-Type: application/json

{
    "name": "Paloma Loaiza Correa",
    "password": "palomita03",
    "email": "paloma0330@gmail.com"
}

###

DELETE {{api}}/users/18/delete

###

POST {{api}}/login
Content-Type: application/json

{
    "email": "gloria@gmail.com",
    "password": "glori99"
}


###

GET {{api}}/15/savings

###

POST {{api}}/15/newSaving
Content-Type: application/json

{
    "description": "ahorro",
    "date": "2023-06-18 03:27:13",
    "annualInterest": 0.13,
    "entity": "nequi",
    "amount": 200000
}

###
GET {{api}}/15/savings
